version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8080'
    depends_on:
      - db
    networks:
      - dev-network

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-data: {}

networks:
  dev-network:
    driver: bridge